// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NeighborhoodGroceryApp;
//
//    var groceryStoreModel = GroceryStoreModel.FromJson(jsonString);

namespace NeighborhoodGroceryApp
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GroceryStoreModel
    {
        [JsonProperty(":@computed_region_43wa_7qmu")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegion43Wa7Qmu { get; set; }

        [JsonProperty("zip_code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ZipCode { get; set; }

        [JsonProperty("buffer_size")]
        public BufferSize BufferSize { get; set; }

        [JsonProperty("license_id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? LicenseId { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("census_tract")]
        public string CensusTract { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("y_coordinate")]
        public string YCoordinate { get; set; }

        [JsonProperty("store_name")]
        public string StoreName { get; set; }

        [JsonProperty("community_area_name")]
        public string CommunityAreaName { get; set; }

        [JsonProperty(":@computed_region_rpca_8um6")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionRpca8Um6 { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty(":@computed_region_awaf_s7ux")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionAwafS7Ux { get; set; }

        [JsonProperty("community_area")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CommunityArea { get; set; }

        [JsonProperty("x_coordinate")]
        public string XCoordinate { get; set; }

        [JsonProperty("ward")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Ward { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty(":@computed_region_bdys_3d7i")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionBdys3D7I { get; set; }

        [JsonProperty(":@computed_region_6mkv_f3dw")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegion6MkvF3Dw { get; set; }

        [JsonProperty("census_block", NullValueHandling = NullValueHandling.Ignore)]
        public string CensusBlock { get; set; }

        [JsonProperty("account_number", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? AccountNumber { get; set; }

        [JsonProperty(":@computed_region_vrxf_vc4k")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ComputedRegionVrxfVc4K { get; set; }

        [JsonProperty("square_feet", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? SquareFeet { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("needs_recoding")]
        public bool NeedsRecoding { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }
    }

    public enum BufferSize { A, B };

    public partial class GroceryStoreModel
    {
        public static GroceryStoreModel[] FromJson(string json) => JsonConvert.DeserializeObject<GroceryStoreModel[]>(json, NeighborhoodGroceryApp.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GroceryStoreModel[] self) => JsonConvert.SerializeObject(self, NeighborhoodGroceryApp.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                BufferSizeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class BufferSizeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BufferSize) || t == typeof(BufferSize?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "A":
                    return BufferSize.A;
                case "B":
                    return BufferSize.B;
            }
            throw new Exception("Cannot unmarshal type BufferSize");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (BufferSize)untypedValue;
            switch (value)
            {
                case BufferSize.A:
                    serializer.Serialize(writer, "A");
                    return;
                case BufferSize.B:
                    serializer.Serialize(writer, "B");
                    return;
            }
            throw new Exception("Cannot marshal type BufferSize");
        }

        public static readonly BufferSizeConverter Singleton = new BufferSizeConverter();
    }
}
