// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NeighborhoodGroceryApp;
//
//    var HousingModel = HousingModel.FromJson(jsonString);

namespace NeighborhoodGroceryApp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class HousingModel
    {
        [JsonProperty("Community_Area")]
        public string CommunityArea { get; set; }

        [JsonProperty("Community_Area_Number")]
        public long CommunityAreaNumber { get; set; }

        [JsonProperty("Propert_Type")]
        public string PropertType { get; set; }

        [JsonProperty("Propert_Name")]
        public string PropertName { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Zip_Code")]
        public long ZipCode { get; set; }

        [JsonProperty("Phone_Number")]
        public string PhoneNumber { get; set; }

        [JsonProperty("Management_Company")]
        public string ManagementCompany { get; set; }

        [JsonProperty("Units")]
        public long Units { get; set; }

        [JsonProperty("Buffer_Size")]
        public string BufferSize { get; set; }

        [JsonProperty("License_ID")]
        public long LicenseId { get; set; }

        [JsonProperty("Census_Tract")]
        public long CensusTract { get; set; }

        [JsonProperty("Store_Name")]
        public string StoreName { get; set; }

        [JsonProperty("Ward")]
        public long Ward { get; set; }

        [JsonProperty("Longtitude")]
        public double Longtitude { get; set; }

        [JsonProperty("Census_Block")]
        public string CensusBlock { get; set; }

        [JsonProperty("Account_Number")]
        public long AccountNumber { get; set; }

        [JsonProperty("Square_feet")]
        public string SquareFeet { get; set; }
    }

    public partial class HousingModel
    {
        public static HousingModel[] FromJson(string json) => JsonConvert.DeserializeObject<HousingModel[]>(json, NeighborhoodGroceryApp.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this HousingModel[] self) => JsonConvert.SerializeObject(self, NeighborhoodGroceryApp.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
